// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory.proto

package go_micro_srv_inventorys

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Inv struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	UnitPrice            int64    `protobuf:"varint,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Stock                int64    `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedTime          int64    `protobuf:"varint,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inv) Reset()         { *m = Inv{} }
func (m *Inv) String() string { return proto.CompactTextString(m) }
func (*Inv) ProtoMessage()    {}
func (*Inv) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{1}
}

func (m *Inv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inv.Unmarshal(m, b)
}
func (m *Inv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inv.Marshal(b, m, deterministic)
}
func (m *Inv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inv.Merge(m, src)
}
func (m *Inv) XXX_Size() int {
	return xxx_messageInfo_Inv.Size(m)
}
func (m *Inv) XXX_DiscardUnknown() {
	xxx_messageInfo_Inv.DiscardUnknown(m)
}

var xxx_messageInfo_Inv proto.InternalMessageInfo

func (m *Inv) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Inv) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Inv) GetUnitPrice() int64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Inv) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Inv) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Inv) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Request struct {
	BookId               int64    `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Bookname             int64    `protobuf:"varint,2,opt,name=bookname,proto3" json:"bookname,omitempty"`
	Bookprice            int64    `protobuf:"varint,3,opt,name=bookprice,proto3" json:"bookprice,omitempty"`
	Bookuseid            int64    `protobuf:"varint,4,opt,name=bookuseid,proto3" json:"bookuseid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Request) GetBookname() int64 {
	if m != nil {
		return m.Bookname
	}
	return 0
}

func (m *Request) GetBookprice() int64 {
	if m != nil {
		return m.Bookprice
	}
	return 0
}

func (m *Request) GetBookuseid() int64 {
	if m != nil {
		return m.Bookuseid
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Inv                  *Inv     `protobuf:"bytes,3,opt,name=inv,proto3" json:"inv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetInv() *Inv {
	if m != nil {
		return m.Inv
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "go.micro.srv.inventorys.Error")
	proto.RegisterType((*Inv)(nil), "go.micro.srv.inventorys.Inv")
	proto.RegisterType((*Request)(nil), "go.micro.srv.inventorys.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.inventorys.Response")
}

func init() { proto.RegisterFile("inventory.proto", fileDescriptor_7173caedb7c6ae96) }

var fileDescriptor_7173caedb7c6ae96 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x4e, 0xeb, 0x30,
	0x10, 0x7e, 0x6e, 0x9a, 0xb4, 0x9d, 0x4a, 0x0f, 0xc9, 0x42, 0x10, 0x55, 0x15, 0x0a, 0x59, 0x75,
	0x95, 0x45, 0xcb, 0x0d, 0x10, 0x8b, 0x6c, 0x00, 0x19, 0x2e, 0xd0, 0xc6, 0x03, 0x58, 0x6d, 0xec,
	0x60, 0x27, 0x91, 0x7a, 0x05, 0xce, 0x01, 0xf7, 0x44, 0x76, 0xd2, 0x34, 0x2c, 0xca, 0x8a, 0xdd,
	0x7c, 0x3f, 0x93, 0xf9, 0x32, 0x63, 0x38, 0x13, 0xb2, 0x46, 0x59, 0x2a, 0xbd, 0x4f, 0x0a, 0xad,
	0x4a, 0x45, 0x2f, 0x5f, 0x55, 0x92, 0x8b, 0x4c, 0xab, 0xc4, 0xe8, 0x3a, 0xe9, 0x54, 0x13, 0xaf,
	0xc0, 0xbf, 0xd3, 0x5a, 0x69, 0x4a, 0x61, 0x98, 0x29, 0x8e, 0x21, 0x89, 0xc8, 0xc2, 0x67, 0xae,
	0xa6, 0x17, 0x10, 0x70, 0x2c, 0xd7, 0x62, 0x17, 0x0e, 0x22, 0xb2, 0x98, 0xb0, 0x16, 0xc5, 0x5f,
	0x04, 0xbc, 0x54, 0xd6, 0xf4, 0x3f, 0x0c, 0x04, 0x77, 0x1d, 0x1e, 0x1b, 0x08, 0x6e, 0xfd, 0x1b,
	0xa5, 0xb6, 0x29, 0x77, 0x7e, 0x8f, 0xb5, 0x88, 0xce, 0x61, 0x52, 0x49, 0x51, 0x3e, 0x6a, 0x91,
	0x61, 0xe8, 0x39, 0xe9, 0x48, 0xd0, 0x73, 0xf0, 0x4d, 0xa9, 0xb2, 0x6d, 0x38, 0x74, 0x4a, 0x03,
	0x68, 0x04, 0xd3, 0x4c, 0xe3, 0xba, 0x44, 0xfe, 0x2c, 0x72, 0x0c, 0x03, 0xa7, 0xf5, 0x29, 0xeb,
	0xa8, 0x0a, 0xde, 0x39, 0x46, 0x8d, 0xa3, 0x47, 0xc5, 0x7b, 0x18, 0x31, 0x7c, 0xaf, 0xd0, 0x94,
	0xbd, 0x68, 0xe4, 0x47, 0xb4, 0x19, 0x8c, 0x6d, 0x25, 0xd7, 0x39, 0xb6, 0xa1, 0x3b, 0x6c, 0x63,
	0xdb, 0xba, 0xe8, 0xc7, 0xee, 0x88, 0x83, 0x5a, 0x19, 0x14, 0xbc, 0x8d, 0x7e, 0x24, 0xe2, 0x0f,
	0x02, 0x63, 0x86, 0xa6, 0x50, 0xd2, 0x20, 0x0d, 0x61, 0x64, 0xaa, 0x2c, 0x43, 0x63, 0xdc, 0xf4,
	0x31, 0x3b, 0x40, 0x7a, 0x03, 0x3e, 0xda, 0xf5, 0xbb, 0xd9, 0xd3, 0xe5, 0x55, 0x72, 0xe2, 0x4e,
	0x89, 0x3b, 0x12, 0x6b, 0xcc, 0x34, 0x01, 0x4f, 0xc8, 0xda, 0x45, 0x9a, 0x2e, 0xe7, 0x27, 0x7b,
	0x52, 0x59, 0x33, 0x6b, 0x5c, 0x7e, 0x12, 0x20, 0x29, 0xbd, 0x07, 0xff, 0xe9, 0x0d, 0x77, 0x3b,
	0x1a, 0x9d, 0xec, 0x68, 0xb7, 0x35, 0xbb, 0xfe, 0xc5, 0xd1, 0xfc, 0x53, 0xfc, 0x8f, 0x3e, 0x40,
	0x70, 0xab, 0xe4, 0x8b, 0xc8, 0xff, 0xe8, 0x83, 0x9b, 0xc0, 0xbd, 0xd5, 0xd5, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x3f, 0x46, 0x11, 0xbe, 0x02, 0x00, 0x00,
}
