// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: inventory.proto

package go_micro_srv_inventorys

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for I service

type IService interface {
	Shell(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Confim(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type iService struct {
	c    client.Client
	name string
}

func NewIService(name string, c client.Client) IService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.inventorys"
	}
	return &iService{
		c:    c,
		name: name,
	}
}

func (c *iService) Shell(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "I.Shell", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iService) Confim(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "I.Confim", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for I service

type IHandler interface {
	Shell(context.Context, *Request, *Response) error
	Confim(context.Context, *Request, *Response) error
}

func RegisterIHandler(s server.Server, hdlr IHandler, opts ...server.HandlerOption) error {
	type i interface {
		Shell(ctx context.Context, in *Request, out *Response) error
		Confim(ctx context.Context, in *Request, out *Response) error
	}
	type I struct {
		i
	}
	h := &iHandler{hdlr}
	return s.Handle(s.NewHandler(&I{h}, opts...))
}

type iHandler struct {
	IHandler
}

func (h *iHandler) Shell(ctx context.Context, in *Request, out *Response) error {
	return h.IHandler.Shell(ctx, in, out)
}

func (h *iHandler) Confim(ctx context.Context, in *Request, out *Response) error {
	return h.IHandler.Confim(ctx, in, out)
}
