apiVersion: v1
kind: Service
metadata:
  name: micro-registry
  namespace: default
  labels:
    name: micro-registry
    micro: service
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    name: micro-registry
    micro: service
