// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay.proto

package go_micro_srv_pay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Commoditynumber      string   `protobuf:"bytes,1,opt,name=commoditynumber,proto3" json:"commoditynumber,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCommoditynumber() string {
	if m != nil {
		return m.Commoditynumber
	}
	return ""
}

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Payurl               string   `protobuf:"bytes,2,opt,name=payurl,proto3" json:"payurl,omitempty"`
	TimeoutExpress       string   `protobuf:"bytes,3,opt,name=timeout_express,json=timeoutExpress,proto3" json:"timeout_express,omitempty"`
	OutTradeNo           string   `protobuf:"bytes,4,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetPayurl() string {
	if m != nil {
		return m.Payurl
	}
	return ""
}

func (m *Response) GetTimeoutExpress() string {
	if m != nil {
		return m.TimeoutExpress
	}
	return ""
}

func (m *Response) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.Usrv.pay.Request")
	proto.RegisterType((*Response)(nil), "go.micro.Usrv.pay.Response")
}

func init() { proto.RegisterFile("pay.proto", fileDescriptor_0564d675d5c516e0) }

var fileDescriptor_0564d675d5c516e0 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xad, 0xab, 0xdd, 0xdd, 0x41, 0x5c, 0x09, 0xa2, 0x75, 0x4f, 0x4b, 0x2f, 0xee, 0x29,
	0x07, 0x7d, 0x02, 0x11, 0x0f, 0x7a, 0x50, 0x29, 0x5e, 0x3c, 0x95, 0xb4, 0x1d, 0x24, 0x60, 0x3a,
	0x71, 0x92, 0x88, 0x79, 0x00, 0xdf, 0x5b, 0xda, 0xc6, 0xcb, 0xb2, 0xc7, 0xef, 0x9b, 0x9f, 0x1f,
	0xe6, 0x87, 0xa5, 0x55, 0x51, 0x5a, 0x26, 0x4f, 0xe2, 0xec, 0x83, 0xa4, 0xd1, 0x2d, 0x93, 0x74,
	0xfc, 0x2d, 0xad, 0x8a, 0x65, 0x03, 0xf3, 0x0a, 0xbf, 0x02, 0x3a, 0x2f, 0xb6, 0xb0, 0x6a, 0xc9,
	0x18, 0xea, 0xb4, 0x8f, 0x7d, 0x30, 0x0d, 0x72, 0x91, 0x6d, 0xb2, 0xed, 0xb2, 0xda, 0xd5, 0xe2,
	0x12, 0xe6, 0xc1, 0x21, 0xd7, 0xba, 0x2b, 0x0e, 0xc7, 0x44, 0x3e, 0xe0, 0x63, 0x27, 0xce, 0xe1,
	0xd8, 0xb2, 0x6e, 0xb1, 0x98, 0x8d, 0x7a, 0x82, 0xf2, 0x37, 0x83, 0x45, 0x85, 0xce, 0x52, 0xef,
	0x50, 0x5c, 0x40, 0xee, 0xbc, 0xf2, 0xc1, 0xa5, 0xf2, 0x44, 0x83, 0xb7, 0x2a, 0x06, 0xfe, 0xfc,
	0xaf, 0x9c, 0x48, 0x5c, 0xc3, 0xca, 0x6b, 0x83, 0x14, 0x7c, 0x8d, 0x3f, 0x96, 0xd1, 0xb9, 0x54,
	0x7e, 0x9a, 0xf4, 0xc3, 0x64, 0xc5, 0x06, 0x4e, 0x86, 0x90, 0x67, 0xd5, 0x61, 0xdd, 0x53, 0x71,
	0x34, 0xa6, 0x80, 0x82, 0x7f, 0x1b, 0xd4, 0x33, 0xdd, 0x3c, 0xc1, 0xec, 0xf5, 0xee, 0x5d, 0xdc,
	0xc3, 0xe2, 0x85, 0x3b, 0x64, 0xab, 0xa2, 0xb8, 0x92, 0xbb, 0x8b, 0xc8, 0x34, 0xc7, 0x7a, 0xbd,
	0xef, 0x34, 0x3d, 0x51, 0x1e, 0x34, 0xf9, 0x38, 0xe8, 0xed, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x14, 0xeb, 0x6a, 0x78, 0x5d, 0x01, 0x00, 0x00,
}
