// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pay.proto

package go_micro_srv_pay

import (
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

import (
	"context"
	"github.com/micro/go-micro/client"
	"github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PAY service

type PAYService interface {
	Orderpay(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type pAYService struct {
	c    client.Client
	name string
}

func NewPAYService(name string, c client.Client) PAYService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.Usrv.pay"
	}
	return &pAYService{
		c:    c,
		name: name,
	}
}

func (c *pAYService) Orderpay(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PAY.Orderpay", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PAY service

type PAYHandler interface {
	Orderpay(context.Context, *Request, *Response) error
}

func RegisterPAYHandler(s server.Server, hdlr PAYHandler, opts ...server.HandlerOption) error {
	type pAY interface {
		Orderpay(ctx context.Context, in *Request, out *Response) error
	}
	type PAY struct {
		pAY
	}
	h := &pAYHandler{hdlr}
	return s.Handle(s.NewHandler(&PAY{h}, opts...))
}

type pAYHandler struct {
	PAYHandler
}

func (h *pAYHandler) Orderpay(ctx context.Context, in *Request, out *Response) error {
	return h.PAYHandler.Orderpay(ctx, in, out)
}
