// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consumer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	CreatedTime          uint64   `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          uint64   `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetCreatedTime() uint64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *User) GetUpdatedTime() uint64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.Usrv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.Usrv.user.Response")
	proto.RegisterType((*User)(nil), "go.micro.Usrv.user.user")
}

func init() { proto.RegisterFile("consumer.proto", fileDescriptor_376dcb7dada8cc1b) }

var fileDescriptor_376dcb7dada8cc1b = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xed, 0x9f, 0x5d, 0xd7, 0x59, 0x58, 0x74, 0x0e, 0x5a, 0xea, 0xa5, 0xf4, 0xb4, 0x20,
	0xf4, 0xb0, 0x9e, 0xbc, 0x0a, 0xde, 0x04, 0x21, 0xe8, 0x03, 0xd4, 0x66, 0x28, 0x39, 0xb4, 0xa9,
	0x99, 0xc4, 0xbd, 0xfa, 0x0a, 0xbe, 0xb1, 0x24, 0x2d, 0xa5, 0xe0, 0xde, 0xf6, 0x12, 0x66, 0xbe,
	0x7c, 0xf9, 0x65, 0xf2, 0x05, 0x76, 0x8d, 0xee, 0xd9, 0x75, 0x64, 0xaa, 0xc1, 0x68, 0xab, 0xf1,
	0xa6, 0xd5, 0x55, 0xa7, 0x1a, 0xa3, 0x2b, 0x36, 0xdf, 0x95, 0x63, 0x32, 0xe5, 0x13, 0x5c, 0x0a,
	0xfa, 0x72, 0xc4, 0x16, 0x11, 0xd2, 0xbe, 0xee, 0x28, 0x8b, 0x8a, 0x68, 0x7f, 0x25, 0x42, 0x8d,
	0x39, 0x6c, 0x86, 0x9a, 0xf9, 0xa8, 0x8d, 0xcc, 0xe2, 0xa0, 0xcf, 0x7d, 0xf9, 0x06, 0x1b, 0x41,
	0x3c, 0xe8, 0x9e, 0x09, 0x1f, 0x20, 0xf5, 0xb8, 0x70, 0x76, 0x7b, 0xb8, 0xab, 0xfe, 0x5d, 0x14,
	0x16, 0x11, 0x4c, 0x78, 0x0b, 0x6b, 0xb6, 0xb5, 0x75, 0x3c, 0x21, 0xa7, 0xae, 0xfc, 0x89, 0x46,
	0x0a, 0xee, 0x20, 0x56, 0x32, 0xb0, 0x12, 0x11, 0x2b, 0x39, 0x4f, 0x16, 0x2f, 0x26, 0xbb, 0x86,
	0x64, 0x38, 0xca, 0x2c, 0x09, 0x92, 0x2f, 0xb1, 0x80, 0x6d, 0x63, 0xa8, 0xb6, 0x24, 0xdf, 0x55,
	0x47, 0x59, 0x5a, 0x44, 0xfb, 0x54, 0x2c, 0x25, 0xef, 0x70, 0x83, 0x9c, 0x1d, 0xab, 0xd1, 0xb1,
	0x90, 0x0e, 0xbf, 0x11, 0xa4, 0x1f, 0x7e, 0x84, 0x67, 0x58, 0xbd, 0xea, 0x56, 0xf5, 0x98, 0x9f,
	0x78, 0xcb, 0x94, 0x58, 0x7e, 0x7f, 0x72, 0x6f, 0x8c, 0xa4, 0xbc, 0xc0, 0x17, 0x1f, 0x50, 0xab,
	0xd8, 0x92, 0x39, 0x03, 0xf3, 0xb9, 0x0e, 0x9f, 0xf7, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x75,
	0x32, 0xaf, 0x11, 0xce, 0x01, 0x00, 0x00,
}
